### ISSUE TITLE
Is it possible to use our own Registry?

### ISSUE THREAD

**Issue by KamranAzeem** [Praqma/LearnKubernetes#1]
Is it possible to use our own registry by specifying it in the local-registry service configuration file? If yes, what happens when we pull some images which are **not** in our registry? How would kubernetes / nodes know to pull those images from Docker hub?

**Comment by Andrey9kin** [comment]
We are using local registry for Jenkins as code
https://github.com/Praqma/JenkinsAsCodeReference/
in order to use it you need to include registry name into the image name
most probably it will pull images from docker hub and act as a proxy but I haven't tryed that

**Comment by KamranAzeem** [comment]
So I see that it is better to let the "local-registry" run on master and point to the docker hub. For any containers requiring our custom images from our inhouse registry, we can specify that in the pod or deployment config/yaml file, such as:

```
   spec:
      containers:
      - name: xyz
        image: 10.239.32.81:5000/xyz:0.2.1-SNAPSHOT
```
